### ISSUE TITLE
Same as `npm docs`?

### ISSUE THREAD

**Issue by goldcaddy77** [eush77/npm-open#1]
Hi, is this the same as running `npm docs <package-name>`?

**Comment by eush77** [comment]
Hi,

Functionally, it's the same, but implementation differs.

`npm docs` takes a package name and derives the web address from the registry by downloading the latest metadata.

`npm-open` takes a directory on disk the package is installed in and derives the web address from its `package.json`. This saves one request.

**Comment by goldcaddy77** [comment]
Gotcha, thanks!
